Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  IgnoredMethods:
    - build_ghost_command
    - mysql2_ghost_connection

Metrics/ModuleLength:
  Exclude:
    - lib/ghost_adapter/config.rb

Metrics/AbcSize:
  IgnoredMethods:
    - build_ghost_command
    - mysql2_ghost_connection

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - mysql2_ghost_connection

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  NewCops: enable
