Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  Max: 150

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  IgnoredMethods:
    - build_ghost_command
    - mysql2_ghost_connection

Metrics/ModuleLength:
  CountAsOne:
    - 'array'
    - 'hash'
    - 'heredoc'
  Exclude:
    - lib/ghost_adapter/config.rb

Metrics/AbcSize:
  IgnoredMethods:
    - build_ghost_command
    - mysql2_ghost_connection

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - mysql2_ghost_connection

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  NewCops: enable
