language: ruby
rvm: 2.7

cache:
  bundler: true

before_install:
  - bundle install --jobs=3 --path=${BUNDLE_PATH:-vendor/bundle}

stages:
  - name: Rubocop
    if: type = pull_request OR branch = main
  - name: Tests
    if: type = pull_request OR branch = main

jobs:
  include:
    - stage: Rubocop
      name: Run rubocop
      script:
        - bundle exec rake rubocop
    - stage: Tests
      name: Run specs
      script:
        - bundle exec rake spec
