name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '45 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1
        with:
          ruby-version: "3.2"
      - name: Install gems
        run: BUNDLE_GEMFILE=gemfiles/activerecord-7.2.Gemfile bundle install
      - name: Run rubocop
        run: BUNDLE_GEMFILE=gemfiles/activerecord-7.2.Gemfile bundle exec rake rubocop
      - name: Run tests
        run: BUNDLE_GEMFILE=gemfiles/activerecord-7.2.Gemfile bundle exec rspec
